# we create a Docker image from source code 
version: '3.3'
services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    #image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Hung@02011999"
    ports:
      - 1435:1433
    volumes:
      - my-volume:/var/opt/mssql
volumes:
  my-volume:
# Create container, netword,... from "docker compose " file: 
  # -d: (detach mode) deamon/background mode
  # docker compose up -d
# if you want to start only (chỉ một) specified (được chỉ định) services/container:
  # docker compose up -d dev-database (name container) -d
# docker compose down : Rollback docker compose
# docker logs "name container": watch log run of container
# how to remove containers+volumes
# docker compose rm dev-database --stop --force --volumes 